<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSoJobTM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSoJobTM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSoJobTM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSoJobTM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSoJobTM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SoJobTM',
    'container.build_id' => 'cf6ffc99',
    'container.build_time' => 1593532378,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSoJobTM');
